### ISSUE TITLE
Any Language | Any Pattern

### ISSUE THREAD

**Issue by aritraroy24** [aritraroy24/HACKTOBERFEST2021_PATTERN#3]
### 👉 Please read the steps described in the documentation carefully. You have to submit a code, screenshot of the output, your details, and your photo (All files should be named by your username). Otherwise, no PR will be merged.

⚡ For beginners
⚡ Code any pattern you like
⚡ Code in any language you want
⚡ Fork and Star the repo
⚡ Follow @aritraroy24 
⚡ Hacktoberfest Accepted
⚡ Modified for HACKTOBERFEST-2021

## 💥 Rule for [Multiple PRs](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN/blob/master/README.md#-what-you-need-to-do-for-multiple-prs-)

-------
👨‍💻👨‍💻👨‍💻 HAPPY HACKTOBERFEST-2021 👨‍💻👨‍💻👨‍💻

**Comment by aortiz24** [comment]
@aritraroy24, Can I work on this? It's my first time at Hacktoberfest!

**Comment by aritraroy24** [comment]
@aortiz24 ,  Surely you can. It's for beginners only.
"pattern" means any type of design using any type of loop. I have given example in the repo, check that for reference. Also, you can find lots of examples on youtube. Go ahead for your first PR. Happy coding & Happy HACKTOBERFEST-2020 👨‍💻👨‍💻👨‍💻

**Comment by aortiz24** [comment]
I submitted a pull request for this repo and hacktoberfest said it was ineligible? Why is that?

**Comment by aritraroy24** [comment]
@aortiz24 I've no idea why that happened but I talked to @sayanmondal2098, who has also contributed to my repo. But his PR has been counted as a valid PR in the hacktoberfest event.

**Comment by GC2002** [comment]
Hi! I would like to work on it. Please assign it to me

**Comment by aritraroy24** [comment]
@GC2002  it's open for all. Please read the [README.md](https://github.com/aritraroy24/HACKTOBERFEST2020_pattern/blob/master/README.md) file and make your contribution.😊😊😊

**Comment by AxelLawliet** [comment]
Can I submit the code for any other distinct pattern?

**Comment by aritraroy24** [comment]
@AxelLawliet sure...go ahead...but keep two things in mind:
1) as Hacktoberfest has not started yet, if you do the PR before October 1, it'll not be counted in the Hacktoberfest
2) you have to follow all the steps...if any step is missing, the PR will not be merged

**Comment by Kirti1807** [comment]
@aritraroy24 
will I have to create any issue or can I directly make a PR in this repo

**Comment by aritraroy24** [comment]
@Kirti1807 no need to create another issue to PR a new pattern and your details...just make sure to complete all the steps and you have fulfilled the eligibility criteria for a successful PR...otherwise, the PR will be marked as invalid...
But if you find any bug or issue in the existing code, you can create an issue addressing that...

**Comment by Abhicoder03** [comment]
Hey @aritraroy24 I want to work on this under Hacktoberfest 2021. Will you assign me or I'll directly PR.

**Comment by tausiq2003** [comment]
@Abhicoder03  you can directly PR

**Comment by Abhicoder03** [comment]
ok.

**Comment by tausiq2003** [comment]
add hacktoberfest tag

**Comment by aritraroy24** [comment]
@tausiq2003 @Abhicoder03 please keep in mind, any PR, sent before October 1 and after October 31 will not be counted in Hacktoberfest

**Comment by tausiq2003** [comment]
oh my god my pull requests are merged

**Comment by tausiq2003** [comment]
what will I do now

**Comment by aritraroy24** [comment]
@tausiq2003 relax...you can do as many PR as you want to a single repo....and nothing to do with merging....you have to send the PR in the month of October...it can be open PR.... that will also be merged ...but you have to send in the month of October....if you want to send multiple PR in this repo....most welcome....just read the thread of @NeilSayok in closed PR section to know the rules....no necessary to add any tag....my repo has that

**Comment by tausiq2003** [comment]
wait @aritraroy24 can I add another pattern on october 1 without updating Contributors.md and adding Photos, so that my pull request will count.

**Comment by aritraroy24** [comment]
@tausiq2003 sure....but I'll update the rule to send multiple PRs by today....just follow along

**Comment by tausiq2003** [comment]
Thank you @aritraroy24 but for me specially I have not to update the contibutors.md and my photo because its in the master branch.

**Comment by ravi-varma-ankam** [comment]
Can I work on this issue for hacktoberfest2021 ?

**Comment by sahooankeeta** [comment]
**@aortiz24** Can I work on this for Hacktoberfest 2021?

**Comment by Sangameshdavey** [comment]
@aortiz24
This is my first time on hacktober fest,
can I please work on this?

**Comment by aritraroy24** [comment]
> Thank you @aritraroy24 but for me specially I have not to update the contibutors.md and my photo because its in the master branch.

@tausiq2003 I have updated the [rule for multiple PRs](https://github.com/aritraroy24/HACKTOBERFEST2021_PATTERN/blob/master/README.md#-what-you-need-to-do-for-multiple-prs-)...please check that.

**Comment by aritraroy24** [comment]
> Can I work on this issue for hacktoberfest2021 ?

@ravi-varma-ankam, indeed you can....but please be sure to send a PR between October 1 and October 31 (based on PST timezone)....otherwise, that will not be counted in Hacktoberfest...if you have already submitted one, then that will not be counted in Hacktoberfest 2021...again, you can send multiple PRs to a single repo...all will be counted if those fall in the time range

**Comment by aritraroy24** [comment]
> **@aortiz24** Can I work on this for Hacktoberfest 2021?

@sahooankeeta , indeed you can....but please be sure to send a PR between October 1 and October 31 (based on PST timezone)....otherwise, that will not be counted in Hacktoberfest...if you have already submitted one, then that will not be counted in Hacktoberfest 2021...again, you can send multiple PRs to a single repo...all will be counted if those fall in the time range

**Comment by aritraroy24** [comment]
> @aortiz24 This is my first time on hacktober fest, can I please work on this?

@Sangameshdavey, indeed you can....but please be sure to send a PR between October 1 and October 31 (based on PST timezone)....otherwise, that will not be counted in Hacktoberfest...if you have already submitted one, then that will not be counted in Hacktoberfest 2021...again, you can send multiple PRs to a single repo...all will be counted if those fall in the time range

**Comment by satkar2001** [comment]
hi i have requested a PR please accept

**Comment by Bhavik-Jikadara** [comment]
issue

**Comment by Dulyaaa** [comment]
@aortiz24 I've made a new pattern using c language and it's an upside-down triangle.

**Comment by wafarifki** [comment]
thank you sir

**Comment by saisumanthkumar** [comment]
@aortiz24 Added new pattern in python language PR #103. 
please accept sir

**Comment by Shubham56-droid** [comment]
hi, there I would like to put my pattern too pls assign the issue to me.

**Comment by rustzz-27** [comment]
Hello,
I want to contribute a pattern under hacktoberfest 2021. So, pls assign me this issue

Thanks

**Comment by aritraroy24** [comment]
@rustzz-27 @Shubham56-droid no need to assign anyone...you can directly PR to this repository

**Comment by rishabhrathore055** [comment]
pls have a look at #169  my PR
@aortiz24

**Comment by rustzz-27** [comment]
> @rustzz-27 @Shubham56-droid no need to assign anyone...you can directly PR to this repository

okay understood thanks

**Comment by saisumanthkumar** [comment]
@aortiz24 please look into #103

**Comment by rishabhrathore055** [comment]
> @aortiz24 please look into #103

I'm not getting

**Comment by tamojeetK** [comment]
@aritraroy24  Please Check my PR and let me know if any change is required. #176

**Comment by aritraroy24** [comment]
@saisumanthkumar @tamojeetK @rishabhrathore055 I'll check all the PRs one by one....don't worry about merging....as far as they opened without an invalid tag they will be counted as a successful PR...and @aortiz24 is not the owner of the repository, I'm...

**Comment by saisumanthkumar** [comment]
@aritraroy24 I'm mentioning because, delay in merging leads to conflict in my branch as others too editing the file,
Hope understand in the good way

Thank you !!

**Comment by aritraroy24** [comment]
@saisumanthkumar yes, I understood...don't worry...I'll resolve the conflicts by myself😊

**Comment by saisumanthkumar** [comment]
Ok, thank you !! 😊

**Comment by Shubham56-droid** [comment]
hi I have added a star pattern program #139 
pls check it and  merge it, if there is an issue with the file or my contribution pls inform me

**Comment by warmachine028** [comment]
Hi! I have added a Diamond pattern in Kotlin #201 
please can you accept my pull request and merge it :) I have completed all the steps mentioned in the README file. This is my first time in hacktoberfest so if there is a problem please tell me :)

**Comment by avyayjain** [comment]
pls assign me this issue I want to add a new pattern

**Comment by chirayus20** [comment]
I'll work on this.

**Comment by saisumanthkumar** [comment]
#103

**Comment by tb-rules10** [comment]
Done

**Comment by swrnv** [comment]
hey @aortiz24  i have added a PR for hacktoberfest. please accept

**Comment by avyayjain** [comment]
hey pls check my pr i have added

**Comment by Shoray2002** [comment]
hey @aortiz24, I have made a PR for hacktoberfest'21. Plz merge

**Comment by Shubham56-droid** [comment]
hi   @aritraroy24 I have added a star pattern program #139
pls check it and merge it, if there is an issue with the file or my contribution pls inform me

**Comment by arrshsh** [comment]
heyy, i have submitted a code for triangle and reverse triangle star pattern. do check it out.

**Comment by harshita214** [comment]
Sir I have created a pull request, please check it out

**Comment by Shubham56-droid** [comment]
hi, @aritraroy24 I have recreated the pattern program pull request will all updates pls do check it. #319

**Comment by BAKCHODGUNDA** [comment]
Hello! i have added a contribution, please look into it and add the hacktoberfest label on it !

**Comment by s-bh** [comment]
My PR #105 was merged but no hacktoberfest labels attached.

**Comment by avyayjain** [comment]
pls add my pr no #251

**Comment by rebelfire888** [comment]
Accept my PR no #335

**Comment by snehashukkla** [comment]
@aritraroy24 i would like ton contribute to this

**Comment by arpitarunkumaar** [comment]
Hi how can i contribute

**Comment by KrishAgarwal2811** [comment]
Is it necessary to add my real photo?

**Comment by chehak123** [comment]
I would like to work on this issue

**Comment by avyayjain** [comment]
it is saying the project is excluded pls tell me my in the hactberfest website

**Comment by aritraroy24** [comment]
**PLEASE DON'T SEND ANY PR TO THIS REPO AS HACKTOBERFEST HAS EXCLUDED THIS REPO DUE TO A LARGE NUMBER OF PRs. 
They thought those are spam and we can't do anything about it. SO PLEASE STOP SENDING PR TO THIS REPO.**

An article if you want to read more about it: [here](https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/)
