### ISSUE TITLE
contributers.md merging conflict

### ISSUE THREAD

**Issue by Rohitm619** [aritraroy24/HACKTOBERFEST2021_PATTERN#341]
It is saying,
"This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests."

Screenshot - 
![image](https://user-images.githubusercontent.com/68510643/135707061-85c9778d-e6ca-4a7c-ad68-b902bed9715b.png)

**Comment by aritraroy24** [comment]
@Rohitm619 I'll handle that...no need to create another issue
