### ISSUE TITLE
Excluded project in Hactoberfest

### ISSUE THREAD

**Issue by arp99** [aritraroy24/HACKTOBERFEST2021_PATTERN#405]
@aritraroy24 Your repo shows Hacktoberfest excluded
![excluded_project](https://user-images.githubusercontent.com/47218246/135715751-aa7fcc98-32bd-4857-bc34-f3999d00e13f.png)

**Comment by aritraroy24** [comment]
@arp99 I also saw that...but I can't understand why this is happening... but in the **hacktoberfest** topics in GitHub it is showing
![image](https://user-images.githubusercontent.com/65696941/135716120-c1c16ec9-f863-4140-9c0a-321c24d8bfe4.png)

**Comment by saisumanthkumar** [comment]
same problem++ 🤔🤔

**Comment by arp99** [comment]
I think your project is gone, it cannot be included again😭😭😭😭

**Comment by tamojeetK** [comment]
Same issue, can't anything be done in this case?

**Comment by aritraroy24** [comment]
@tamojeetK I couldn't find anything about this problem after searching in Google...I have no idea about it...sorry guys for all the inconveniences

**Comment by arp99** [comment]
> @tamojeetK I couldn't find anything about this problem after searching in Google...I have no idea about it...sorry guys for all the inconveniences

You could just mail them if there is any solution for this

**Comment by aritraroy24** [comment]
**HACKTOBERFEST HAS EXCLUDED THIS REPO DUE TO A LARGE NUMBER OF PRs. 
They thought those are spam and we can't do anything about it. SO PLEASE STOP SENDING PR TO THIS REPO.**

An article if you want to read more about it: [here](https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/)
